In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('habitat_coding.csv', index_col = "id")
data

oxygen_regulation radiation_protection  gravity  food  supplies  \
id                                                                    
1                 1.5                 0.75        0  1.50       0.0   
2                 1.5                    0        0  0.00       0.0   
3                 1.5                  1.5        1  1.50       1.5   
4                 1.5                  1.5        1  0.75       1.5   
5                 1.5                  1.5        1  1.50       0.0   
..                ...                  ...      ...   ...       ...   
60                1.5                  1.5        1  0.75       1.5   
61                1.5                    0        1  0.75       1.5   
62                1.5                  1.5        1  1.50       1.5   
63                1.5                  1.5        1  0.75       1.5   
64                0.0                    0        0  0.75       1.5   

    power_generation  health  communications_facilities  shape  area  \
id                                                                     
1               1.00       1                        1.5   0.75   0.0   
2               1.50       0                        1.5   1.50   1.0   
3               1.50       0                        1.5   0.75   1.0   
4               1.50       0                        1.5   1.50   0.0   
5               0.75       0                        1.5   0.00   0.5   
..               ...     ...                        ...    ...   ...   
60              1.50       1                        1.5   0.00   1.0   
61              1.50       0                        0.0   0.00   1.0   
62              1.50       1                        1.5   1.50   1.0   
63              1.50       1                        1.5   1.50   1.0   
64              1.50       0                        1.5   1.50   0.0   

    transportation  
id                  
1              0.0  
2              0.0  
3              1.0  
4              0.0  
5              1.0  
..             ...  
60             0.0  
61             1.0  
62             1.0  
63             1.0  
64             1.0  

[64 rows x 11 columns]

In [2]:
pd.to_numeric(data["oxygen_regulation"])
data["oxygen_regulation"].unique()

array([1.5 , 0.  , 0.75])

In [3]:
data.loc[data["oxygen_regulation"] == 0, "oxygen_regulation"] = 0
data.loc[data["oxygen_regulation"] == .75, "oxygen_regulation"] = 1
data.loc[data["oxygen_regulation"] == 1.5, "oxygen_regulation"] = 2
data["oxygen_regulation"]

id
1     2.0
2     2.0
3     2.0
4     2.0
5     2.0
     ... 
60    2.0
61    2.0
62    2.0
63    2.0
64    0.0
Name: oxygen_regulation, Length: 64, dtype: float64

In [4]:
data["radiation_protection"] = data["radiation_protection"].str.strip()
data["radiation_protection"] = pd.to_numeric(data["radiation_protection"])
data["radiation_protection"].unique()

array([0.75, 0.  , 1.5 ])

In [5]:
data.loc[data["radiation_protection"] == 0, "radiation_protection"] = 0
data.loc[data["radiation_protection"] == .75, "radiation_protection"] = 1
data.loc[data["radiation_protection"] == 1.5 , "radiation_protection"] = 2
data["radiation_protection"]

id
1     1.0
2     0.0
3     2.0
4     2.0
5     2.0
     ... 
60    2.0
61    0.0
62    2.0
63    2.0
64    0.0
Name: radiation_protection, Length: 64, dtype: float64

In [6]:
data["gravity"].unique()

array([0, 1], dtype=int64)

In [7]:
data["food"].unique()

array([1.5 , 0.  , 0.75])

In [8]:
data.loc[data["food"] == 0, "food"] = 0
data.loc[data["food"] == .75, "food"] = 1
data.loc[data["food"] == 1.5 , "food"] = 2
data["food"]

id
1     2.0
2     0.0
3     2.0
4     1.0
5     2.0
     ... 
60    1.0
61    1.0
62    2.0
63    1.0
64    1.0
Name: food, Length: 64, dtype: float64

In [9]:
data["supplies"].unique()

array([0.  , 1.5 , 0.75])

In [10]:
data.loc[data["supplies"] == 0, "supplies"] = 0
data.loc[data["supplies"] == .75, "supplies"] = 1
data.loc[data["supplies"] == 1.5 , "supplies"] = 2
data["supplies"]

id
1     0.0
2     0.0
3     2.0
4     2.0
5     0.0
     ... 
60    2.0
61    2.0
62    2.0
63    2.0
64    2.0
Name: supplies, Length: 64, dtype: float64

In [11]:
data["power_generation"].unique()

array([1.  , 1.5 , 0.75, 0.  ])

In [12]:
data.loc[data["power_generation"] == 0, "power_generation"] = 0
data.loc[(data["power_generation"] == 1.5) | (data["power_generation"] == 1), "power_generation"] = 2
data.loc[data["power_generation"] == .75, "power_generation"] = 1
data["power_generation"]

id
1     2.0
2     2.0
3     2.0
4     2.0
5     1.0
     ... 
60    2.0
61    2.0
62    2.0
63    2.0
64    2.0
Name: power_generation, Length: 64, dtype: float64

In [13]:
data["health"].unique()

array([1, 0], dtype=int64)

In [14]:
data["communications_facilities"].unique()

array([1.5 , 0.75, 0.  ])

In [15]:
data.loc[data["communications_facilities"] == 0, "communications_facilities"] = 0
data.loc[data["communications_facilities"] == .75, "communications_facilities"] = 1
data.loc[(data["communications_facilities"] == 1.5), "communications_facilities"] = 2
data["communications_facilities"]

id
1     2.0
2     2.0
3     2.0
4     2.0
5     2.0
     ... 
60    2.0
61    0.0
62    2.0
63    2.0
64    2.0
Name: communications_facilities, Length: 64, dtype: float64

In [16]:
data["shape"].unique()

array([0.75, 1.5 , 0.  ])

In [17]:
data.loc[data["shape"] == 0, "shape"] = 0
data.loc[data["shape"] == .75, "shape"] = 1
data.loc[(data["shape"] == 1.5), "shape"] = 2
data["shape"]

id
1     1.0
2     2.0
3     1.0
4     2.0
5     0.0
     ... 
60    0.0
61    0.0
62    2.0
63    2.0
64    2.0
Name: shape, Length: 64, dtype: float64

In [18]:
data["area"].unique()

array([0. , 1. , 0.5])

In [19]:
data.loc[data["area"] == 0, "area"] = 0
data.loc[(data["area"] == 1), "area"] = 2
data.loc[data["area"] == .5, "area"] = 1
data["area"]

id
1     0.0
2     2.0
3     2.0
4     0.0
5     1.0
     ... 
60    2.0
61    2.0
62    2.0
63    2.0
64    0.0
Name: area, Length: 64, dtype: float64

In [20]:
data["transportation"].unique()

array([0. , 1. , 0.5])

In [21]:
data.loc[data["transportation"] == 0, "transportation"] = 0
data.loc[(data["transportation"] == 1), "transportation"] = 2
data.loc[data["transportation"] == .5, "transportation"] = 1
data["transportation"]

id
1     0.0
2     0.0
3     2.0
4     0.0
5     2.0
     ... 
60    0.0
61    2.0
62    2.0
63    2.0
64    2.0
Name: transportation, Length: 64, dtype: float64

In [22]:
data.to_csv("codes_categorized.csv")